# Generated by Django 4.1.7 on 2023-07-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=21)),
                ('Tanggal_Datang', models.DateField()),
                ('Hari_Penginapan', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pulang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=21)),
                ('Tanggal_Pulang', models.DateField()),
                ('Hari_Penginapan', models.CharField(max_length=2)),
                ('Saran_Masukan', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tamu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=20)),
                ('NIK', models.CharField(max_length=20)),
                ('Alamat', models.CharField(max_length=10)),
                ('no_telp', models.CharField(max_length=13)),
                ('KTP', models.ImageField(upload_to='')),
            ],
        ),
    ]
