# Generated by Django 4.1.7 on 2023-07-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DATA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pulang',
            name='Hari_Penginapan',
        ),
    ]
