# Generated by Django 4.1.7 on 2023-07-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DATA', '0003_alter_tamu_alamat_alter_tamu_nik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamu',
            name='KTP',
            field=models.ImageField(upload_to='uploads/image/'),
        ),
    ]
